title: Critical Response: Securing NOVA’s Grid
description: A cybersecurity simulation where a grid-wide blackout tests decision-making, communication, and crisis response.
footer_content: 'Future of Security | Virginia Tech 2025'

theme: just-the-docs
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

just_the_docs:
  search_enabled: true
  show_last_modified_time: true
  show_nav_level: 2
